name: main
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - run: pip install -r requirements.txt
      - run: |
          git config --global user.name 'Github Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: >
          pre-commit-mirror . \
            --entry=mypy \
            --package-name=mypy-dev \
            --language=python --types-or=python --types-or=pyi \
            --args=--ignore-missing-imports,--scripts-are-modules \
            --require-serial
      - name: Push changes to Github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
            git push origin HEAD:refs/heads/main --tags
